name: Build Docker Image
on: 
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      tag:
        required: true
        type: string
      frontend_name: 
        required: true
        type: string
    secrets:
      token: 
        required: true
jobs:
  image:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Download Infra/deploy info
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.frontend_name }}-infra
        path: ${{ github.workspace }}/infra/

    - name: Download build files
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.frontend_name }}-www
        path: ${{ github.workspace }}/infra/www

    - name: Log in to the Github Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ secrets.token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build docker image and push to github repo
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.workspace }}/infra
        push: true
        tags: ghcr.io/${{ github.repository }}/${{ inputs.frontend_name }}:${{ inputs.tag }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
  security_scan:
    name: Run Security Scan
    needs:      
      - image
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v2

    - name: Security scan on docker image
      id: security-scan
      uses: azure/container-scan@v0
      with:
        image-name: ghcr.io/${{ github.repository }}/${{ inputs.frontend_name }}:${{ inputs.tag }}
        username: ${{ inputs.username }}
        password: ${{ secrets.token }}

    - name: Format scan output
      run: |
        pip3 install json2html
        python3 ${{ github.workspace }}/.github/convert2html.py ${{ steps.security-scan.outputs.scan-report-path }} > ./scan.html

    - name: Upload build to artificats
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.frontend_name }}-security-scan
        path: ./scan.html