name: Build App
on: 
  workflow_call:
    inputs:
      HOSTNAME:
        required: true
        type: string
      FRONTEND_NAME: 
        required: true
        type: string
      DOMAIN_SETTINGS:
        required: true
        type: string
      DOMAIN_LOGIN:
        required: true
        type: string
      DOMAIN_PUBLISH:
        required: true
        type: string
      DOMAIN_ENGAGE:
        required: true
        type: string
      DOMAIN_MEASURE:
        required: true
        type: string
      SETTINGS_API:
        required: true
        type: string
      API:
        required: true
        type: string
      AUTH:
        required: true
        type: string
      PUBLISH:
        required: true
        type: string
      BACKEND_DOMAIN_SOCKET:
        required: true
        type: string
      BACKEND_DOMAIN_MEASURE:
        required: true
        type: string
      REDIRECT:
        required: true
        type: string
jobs:
  build:
    name: Application
    runs-on: ubuntu-latest
    container: node:7.6.0-alpine
    steps:     
    - name: Get Code
      uses: actions/checkout@v2

    - name: Get npm cache directory
      id: npm-cache
      run: echo "::set-output name=dir::$(npm config get cache)"

    - name: Setup Cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-${{ inputs.FRONTEND_NAME }}
      
    - name: Install packages
      run: npm install --no-progress --silent
    
    - name: Build
      run: |
        npm run webpack-prod -- \
        --env.hostname=https://${{ inputs.HOSTNAME }} \
        --env.DOMAIN_SETTINGS=https://${{ inputs.DOMAIN_SETTINGS }} \
        --env.DOMAIN_MEASURE=https://${{ inputs.DOMAIN_MEASURE }} \
        --env.DOMAIN_LOGIN=https://${{ inputs.DOMAIN_LOGIN }} \
        --env.DOMAIN_PUBLISH=https://${{ inputs.DOMAIN_PUBLISH }} \
        --env.DOMAIN_ENGAGE=https://${{ inputs.DOMAIN_ENGAGE }} \
        --env.SETTINGS_API=https://${{ inputs.SETTINGS_API }} \
        --env.API=https://${{ inputs.API }} \
        --env.AUTH=https://${{ inputs.AUTH }} \
        --env.PUBLISH=https://${{ inputs.PUBLISH }} \
        --env.BACKEND_DOMAIN_SOCKET=https://${{ inputs.BACKEND_DOMAIN_SOCKET }} \
        --env.BACKEND_DOMAIN_MEASURE=https://${{ inputs.BACKEND_DOMAIN_MEASURE }} \
        --env.DEFAULT_REDIRECTION=http://${{ inputs.REDIRECT }}

    - name: Upload build to artificats
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.FRONTEND_NAME }}-www
        path: ${{ github.workspace }}/www

    - name: Upload infra/deployment info
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.FRONTEND_NAME }}-infra
        path: ${{ github.workspace }}/infra
