name: Deploy App 
on: 
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      ENV_NAME:
        required: true
        type: string
      TAG: 
        required: true
        type: string
      HOSTNAME:
        required: true
        type: string
    secrets:
      KUBECONFIG: 
        required: true

jobs:        
  deploy:
    name: Deploy ${{ inputs.ENV_NAME }} ${{ inputs.APP_NAME }}
    runs-on: ubuntu-latest
    container: iaacautomation/deploy    
    defaults:
      run:
        shell: bash
    steps:
      - name: Download Infra/deploy info
        uses: actions/download-artifact@v2
        with:
          name: infra
          path: infra/

      - name: Get Kubeconfig
        run: |
          mkdir ${HOME}/.kube/ -p
          echo "${{ secrets.KUBECONFIG }}" > ${HOME}/.kube/config

      - name: Run Diff
        run: helm diff upgrade --allow-unreleased --namespace ${{ inputs.ENV_NAME }} ${{ inputs.APP_NAME }} infra/${{ inputs.APP_NAME }}/ 

      - name: Run Install
        run: |
          helm upgrade -i --namespace ${{ inputs.ENV_NAME }} \
            --set image.repository=${{ inputs.ENV_NAME }}-${{ inputs.APP_NAME }} \
            --set image.tag=${{ inputs.TAG }} \
            --set ingress.hosts[0].host=${{ inputs.HOSTNAME }} \
            --values infra/values.yaml ${{ needs.test_app.outputs.APP_NAME }} infra/${{ inputs.APP_NAME }}/